baseURL = "https://nothofagusdombeyis.com"
languageCode = "es"
title = "Nothofagus Dombeyis"
theme = "PaperMod"
defaultTheme = "dark"
disableThemeToggle = true

# PaperMod / RSS expects this in many configs
[params]
  disableSpecial1stPost = true
  author = "Ricardo Vivanco"
  MainSections = ["SobrePensar","Guías","sobre-mi","post","posts","Poemas"]
  disableHLJS = true
  ShowTags = true
  ShowShareButtons = true
  cover = "images/background.JPG"
  ShowPostCover = true
  ShowPostCoverInList = true
  ShowPostCoverInSingle = true

[params.assets]
  favicon = "favicon.ico"
  favicon16x16 = "favicon-16x16.png"
  favicon32x32 = "favicon-32x32.png"

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    style = "monokai"

[menu]
  [[menu.main]]
    name = "SobrePensar"
    url = "/SobrePensar/"
    weight = 10
#  [[menu.main]]
#    name = "Guías"
#    url = "/Guias/"
#    weight = 20
  [[menu.main]]
    name = "Poemas"
    url = "/poemas/"
    weight = 20
  [[menu.main]]
    name = "Sobre mi"
    url = "/sobre-mi/"
    weight = 20

